  CREATE TABLE "PRODUCT" 
   (	"PRODUCT_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"PRODUCT_NAME" VARCHAR2(200) NOT NULL ENABLE, 
	"CATEGORY_ID" NUMBER, 
	"PRICE" NUMBER(10,2), 
	"CREATED_ON" DATE DEFAULT SYSDATE, 
	"GPT_RAW" VARCHAR2(1000), 
	 PRIMARY KEY ("PRODUCT_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "PRODUCT_CATEGORY" 
   (	"CATEGORY_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"CATEGORY_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	 PRIMARY KEY ("CATEGORY_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "PRODUCT" ADD CONSTRAINT "FK_PRODUCT_CATEGORY" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES "PRODUCT_CATEGORY" ("CATEGORY_ID") ENABLE;



